// JWTs without expiry

const ADMIN_AND_USER_SAMPLE_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidHlwZSI6IkFkbWluIiwiaWF0IjoxNjEyMjQ1ODY0fQ.WYZuY28WUCXIZdtyF45UanY1zbpBcjYhXYVkfHpcSfg";

const ADMIN_NOT_USER_SAMPLE_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidHlwZSI6IkFkbWluIiwiaWF0IjoxNjEyMjUyNDgxfQ._yo9CcX-Zrtm84lk-jbKm4LNmysmeESrTA9x4kfOLq8";

const MEMBER_SAMPLE_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidHlwZSI6IkN1c3RvbWVyIiwiaWF0IjoxNjEyMjUyNTAxfQ.KeTTMFoHz7FmNKIs3QzUvBRSk8aGLgqfA9T0ccefp78";

const INVALID_TOKEN = "...";

export default ADMIN_AND_USER_SAMPLE_TOKEN;